// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scoring.proto

package sentinel;

public final class Scoring {
  private Scoring() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ScoreRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sentinel.ScoreRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string tx_id = 1;</code>
     * @return The txId.
     */
    java.lang.String getTxId();
    /**
     * <code>string tx_id = 1;</code>
     * @return The bytes for txId.
     */
    com.google.protobuf.ByteString
        getTxIdBytes();

    /**
     * <code>string user_id = 2;</code>
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     * <code>string user_id = 2;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>double amount = 3;</code>
     * @return The amount.
     */
    double getAmount();

    /**
     * <code>int32 history_count = 4;</code>
     * @return The historyCount.
     */
    int getHistoryCount();

    /**
     * <code>string device_fingerprint = 5;</code>
     * @return The deviceFingerprint.
     */
    java.lang.String getDeviceFingerprint();
    /**
     * <code>string device_fingerprint = 5;</code>
     * @return The bytes for deviceFingerprint.
     */
    com.google.protobuf.ByteString
        getDeviceFingerprintBytes();
  }
  /**
   * Protobuf type {@code sentinel.ScoreRequest}
   */
  public static final class ScoreRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sentinel.ScoreRequest)
      ScoreRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ScoreRequest.newBuilder() to construct.
    private ScoreRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ScoreRequest() {
      txId_ = "";
      userId_ = "";
      deviceFingerprint_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ScoreRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sentinel.Scoring.internal_static_sentinel_ScoreRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sentinel.Scoring.internal_static_sentinel_ScoreRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sentinel.Scoring.ScoreRequest.class, sentinel.Scoring.ScoreRequest.Builder.class);
    }

    public static final int TX_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object txId_ = "";
    /**
     * <code>string tx_id = 1;</code>
     * @return The txId.
     */
    @java.lang.Override
    public java.lang.String getTxId() {
      java.lang.Object ref = txId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txId_ = s;
        return s;
      }
    }
    /**
     * <code>string tx_id = 1;</code>
     * @return The bytes for txId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTxIdBytes() {
      java.lang.Object ref = txId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object userId_ = "";
    /**
     * <code>string user_id = 2;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string user_id = 2;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private double amount_ = 0D;
    /**
     * <code>double amount = 3;</code>
     * @return The amount.
     */
    @java.lang.Override
    public double getAmount() {
      return amount_;
    }

    public static final int HISTORY_COUNT_FIELD_NUMBER = 4;
    private int historyCount_ = 0;
    /**
     * <code>int32 history_count = 4;</code>
     * @return The historyCount.
     */
    @java.lang.Override
    public int getHistoryCount() {
      return historyCount_;
    }

    public static final int DEVICE_FINGERPRINT_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object deviceFingerprint_ = "";
    /**
     * <code>string device_fingerprint = 5;</code>
     * @return The deviceFingerprint.
     */
    @java.lang.Override
    public java.lang.String getDeviceFingerprint() {
      java.lang.Object ref = deviceFingerprint_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceFingerprint_ = s;
        return s;
      }
    }
    /**
     * <code>string device_fingerprint = 5;</code>
     * @return The bytes for deviceFingerprint.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceFingerprintBytes() {
      java.lang.Object ref = deviceFingerprint_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceFingerprint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(txId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, txId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userId_);
      }
      if (java.lang.Double.doubleToRawLongBits(amount_) != 0) {
        output.writeDouble(3, amount_);
      }
      if (historyCount_ != 0) {
        output.writeInt32(4, historyCount_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceFingerprint_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, deviceFingerprint_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(txId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, txId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userId_);
      }
      if (java.lang.Double.doubleToRawLongBits(amount_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, amount_);
      }
      if (historyCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, historyCount_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceFingerprint_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, deviceFingerprint_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sentinel.Scoring.ScoreRequest)) {
        return super.equals(obj);
      }
      sentinel.Scoring.ScoreRequest other = (sentinel.Scoring.ScoreRequest) obj;

      if (!getTxId()
          .equals(other.getTxId())) return false;
      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (java.lang.Double.doubleToLongBits(getAmount())
          != java.lang.Double.doubleToLongBits(
              other.getAmount())) return false;
      if (getHistoryCount()
          != other.getHistoryCount()) return false;
      if (!getDeviceFingerprint()
          .equals(other.getDeviceFingerprint())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TX_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTxId().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (37 * hash) + HISTORY_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getHistoryCount();
      hash = (37 * hash) + DEVICE_FINGERPRINT_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceFingerprint().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sentinel.Scoring.ScoreRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentinel.Scoring.ScoreRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentinel.Scoring.ScoreRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentinel.Scoring.ScoreRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentinel.Scoring.ScoreRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentinel.Scoring.ScoreRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentinel.Scoring.ScoreRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sentinel.Scoring.ScoreRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sentinel.Scoring.ScoreRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sentinel.Scoring.ScoreRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sentinel.Scoring.ScoreRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sentinel.Scoring.ScoreRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sentinel.Scoring.ScoreRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sentinel.ScoreRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sentinel.ScoreRequest)
        sentinel.Scoring.ScoreRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sentinel.Scoring.internal_static_sentinel_ScoreRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sentinel.Scoring.internal_static_sentinel_ScoreRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sentinel.Scoring.ScoreRequest.class, sentinel.Scoring.ScoreRequest.Builder.class);
      }

      // Construct using sentinel.Scoring.ScoreRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        txId_ = "";
        userId_ = "";
        amount_ = 0D;
        historyCount_ = 0;
        deviceFingerprint_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sentinel.Scoring.internal_static_sentinel_ScoreRequest_descriptor;
      }

      @java.lang.Override
      public sentinel.Scoring.ScoreRequest getDefaultInstanceForType() {
        return sentinel.Scoring.ScoreRequest.getDefaultInstance();
      }

      @java.lang.Override
      public sentinel.Scoring.ScoreRequest build() {
        sentinel.Scoring.ScoreRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sentinel.Scoring.ScoreRequest buildPartial() {
        sentinel.Scoring.ScoreRequest result = new sentinel.Scoring.ScoreRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(sentinel.Scoring.ScoreRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.txId_ = txId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.amount_ = amount_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.historyCount_ = historyCount_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.deviceFingerprint_ = deviceFingerprint_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sentinel.Scoring.ScoreRequest) {
          return mergeFrom((sentinel.Scoring.ScoreRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sentinel.Scoring.ScoreRequest other) {
        if (other == sentinel.Scoring.ScoreRequest.getDefaultInstance()) return this;
        if (!other.getTxId().isEmpty()) {
          txId_ = other.txId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        if (other.getHistoryCount() != 0) {
          setHistoryCount(other.getHistoryCount());
        }
        if (!other.getDeviceFingerprint().isEmpty()) {
          deviceFingerprint_ = other.deviceFingerprint_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                txId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                userId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 25: {
                amount_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 32: {
                historyCount_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                deviceFingerprint_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object txId_ = "";
      /**
       * <code>string tx_id = 1;</code>
       * @return The txId.
       */
      public java.lang.String getTxId() {
        java.lang.Object ref = txId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          txId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tx_id = 1;</code>
       * @return The bytes for txId.
       */
      public com.google.protobuf.ByteString
          getTxIdBytes() {
        java.lang.Object ref = txId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tx_id = 1;</code>
       * @param value The txId to set.
       * @return This builder for chaining.
       */
      public Builder setTxId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        txId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string tx_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTxId() {
        txId_ = getDefaultInstance().getTxId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string tx_id = 1;</code>
       * @param value The bytes for txId to set.
       * @return This builder for chaining.
       */
      public Builder setTxIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        txId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string user_id = 2;</code>
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_id = 2;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_id = 2;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        userId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        userId_ = getDefaultInstance().getUserId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 2;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        userId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <code>double amount = 3;</code>
       * @return The amount.
       */
      @java.lang.Override
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>double amount = 3;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(double value) {
        
        amount_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double amount = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        amount_ = 0D;
        onChanged();
        return this;
      }

      private int historyCount_ ;
      /**
       * <code>int32 history_count = 4;</code>
       * @return The historyCount.
       */
      @java.lang.Override
      public int getHistoryCount() {
        return historyCount_;
      }
      /**
       * <code>int32 history_count = 4;</code>
       * @param value The historyCount to set.
       * @return This builder for chaining.
       */
      public Builder setHistoryCount(int value) {
        
        historyCount_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 history_count = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHistoryCount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        historyCount_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object deviceFingerprint_ = "";
      /**
       * <code>string device_fingerprint = 5;</code>
       * @return The deviceFingerprint.
       */
      public java.lang.String getDeviceFingerprint() {
        java.lang.Object ref = deviceFingerprint_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceFingerprint_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string device_fingerprint = 5;</code>
       * @return The bytes for deviceFingerprint.
       */
      public com.google.protobuf.ByteString
          getDeviceFingerprintBytes() {
        java.lang.Object ref = deviceFingerprint_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceFingerprint_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string device_fingerprint = 5;</code>
       * @param value The deviceFingerprint to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceFingerprint(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        deviceFingerprint_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string device_fingerprint = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceFingerprint() {
        deviceFingerprint_ = getDefaultInstance().getDeviceFingerprint();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string device_fingerprint = 5;</code>
       * @param value The bytes for deviceFingerprint to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceFingerprintBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        deviceFingerprint_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sentinel.ScoreRequest)
    }

    // @@protoc_insertion_point(class_scope:sentinel.ScoreRequest)
    private static final sentinel.Scoring.ScoreRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sentinel.Scoring.ScoreRequest();
    }

    public static sentinel.Scoring.ScoreRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ScoreRequest>
        PARSER = new com.google.protobuf.AbstractParser<ScoreRequest>() {
      @java.lang.Override
      public ScoreRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ScoreRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ScoreRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sentinel.Scoring.ScoreRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ScoreResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sentinel.ScoreResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string tx_id = 1;</code>
     * @return The txId.
     */
    java.lang.String getTxId();
    /**
     * <code>string tx_id = 1;</code>
     * @return The bytes for txId.
     */
    com.google.protobuf.ByteString
        getTxIdBytes();

    /**
     * <code>int32 risk_score = 2;</code>
     * @return The riskScore.
     */
    int getRiskScore();

    /**
     * <code>bool ml_used = 3;</code>
     * @return The mlUsed.
     */
    boolean getMlUsed();
  }
  /**
   * Protobuf type {@code sentinel.ScoreResponse}
   */
  public static final class ScoreResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sentinel.ScoreResponse)
      ScoreResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ScoreResponse.newBuilder() to construct.
    private ScoreResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ScoreResponse() {
      txId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ScoreResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sentinel.Scoring.internal_static_sentinel_ScoreResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sentinel.Scoring.internal_static_sentinel_ScoreResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sentinel.Scoring.ScoreResponse.class, sentinel.Scoring.ScoreResponse.Builder.class);
    }

    public static final int TX_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object txId_ = "";
    /**
     * <code>string tx_id = 1;</code>
     * @return The txId.
     */
    @java.lang.Override
    public java.lang.String getTxId() {
      java.lang.Object ref = txId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txId_ = s;
        return s;
      }
    }
    /**
     * <code>string tx_id = 1;</code>
     * @return The bytes for txId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTxIdBytes() {
      java.lang.Object ref = txId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RISK_SCORE_FIELD_NUMBER = 2;
    private int riskScore_ = 0;
    /**
     * <code>int32 risk_score = 2;</code>
     * @return The riskScore.
     */
    @java.lang.Override
    public int getRiskScore() {
      return riskScore_;
    }

    public static final int ML_USED_FIELD_NUMBER = 3;
    private boolean mlUsed_ = false;
    /**
     * <code>bool ml_used = 3;</code>
     * @return The mlUsed.
     */
    @java.lang.Override
    public boolean getMlUsed() {
      return mlUsed_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(txId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, txId_);
      }
      if (riskScore_ != 0) {
        output.writeInt32(2, riskScore_);
      }
      if (mlUsed_ != false) {
        output.writeBool(3, mlUsed_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(txId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, txId_);
      }
      if (riskScore_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, riskScore_);
      }
      if (mlUsed_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, mlUsed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sentinel.Scoring.ScoreResponse)) {
        return super.equals(obj);
      }
      sentinel.Scoring.ScoreResponse other = (sentinel.Scoring.ScoreResponse) obj;

      if (!getTxId()
          .equals(other.getTxId())) return false;
      if (getRiskScore()
          != other.getRiskScore()) return false;
      if (getMlUsed()
          != other.getMlUsed()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TX_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTxId().hashCode();
      hash = (37 * hash) + RISK_SCORE_FIELD_NUMBER;
      hash = (53 * hash) + getRiskScore();
      hash = (37 * hash) + ML_USED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMlUsed());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sentinel.Scoring.ScoreResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentinel.Scoring.ScoreResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentinel.Scoring.ScoreResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentinel.Scoring.ScoreResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentinel.Scoring.ScoreResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sentinel.Scoring.ScoreResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sentinel.Scoring.ScoreResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sentinel.Scoring.ScoreResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sentinel.Scoring.ScoreResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sentinel.Scoring.ScoreResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sentinel.Scoring.ScoreResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sentinel.Scoring.ScoreResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sentinel.Scoring.ScoreResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sentinel.ScoreResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sentinel.ScoreResponse)
        sentinel.Scoring.ScoreResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sentinel.Scoring.internal_static_sentinel_ScoreResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sentinel.Scoring.internal_static_sentinel_ScoreResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sentinel.Scoring.ScoreResponse.class, sentinel.Scoring.ScoreResponse.Builder.class);
      }

      // Construct using sentinel.Scoring.ScoreResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        txId_ = "";
        riskScore_ = 0;
        mlUsed_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sentinel.Scoring.internal_static_sentinel_ScoreResponse_descriptor;
      }

      @java.lang.Override
      public sentinel.Scoring.ScoreResponse getDefaultInstanceForType() {
        return sentinel.Scoring.ScoreResponse.getDefaultInstance();
      }

      @java.lang.Override
      public sentinel.Scoring.ScoreResponse build() {
        sentinel.Scoring.ScoreResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sentinel.Scoring.ScoreResponse buildPartial() {
        sentinel.Scoring.ScoreResponse result = new sentinel.Scoring.ScoreResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(sentinel.Scoring.ScoreResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.txId_ = txId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.riskScore_ = riskScore_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.mlUsed_ = mlUsed_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sentinel.Scoring.ScoreResponse) {
          return mergeFrom((sentinel.Scoring.ScoreResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sentinel.Scoring.ScoreResponse other) {
        if (other == sentinel.Scoring.ScoreResponse.getDefaultInstance()) return this;
        if (!other.getTxId().isEmpty()) {
          txId_ = other.txId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getRiskScore() != 0) {
          setRiskScore(other.getRiskScore());
        }
        if (other.getMlUsed() != false) {
          setMlUsed(other.getMlUsed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                txId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                riskScore_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                mlUsed_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object txId_ = "";
      /**
       * <code>string tx_id = 1;</code>
       * @return The txId.
       */
      public java.lang.String getTxId() {
        java.lang.Object ref = txId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          txId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tx_id = 1;</code>
       * @return The bytes for txId.
       */
      public com.google.protobuf.ByteString
          getTxIdBytes() {
        java.lang.Object ref = txId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tx_id = 1;</code>
       * @param value The txId to set.
       * @return This builder for chaining.
       */
      public Builder setTxId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        txId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string tx_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTxId() {
        txId_ = getDefaultInstance().getTxId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string tx_id = 1;</code>
       * @param value The bytes for txId to set.
       * @return This builder for chaining.
       */
      public Builder setTxIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        txId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int riskScore_ ;
      /**
       * <code>int32 risk_score = 2;</code>
       * @return The riskScore.
       */
      @java.lang.Override
      public int getRiskScore() {
        return riskScore_;
      }
      /**
       * <code>int32 risk_score = 2;</code>
       * @param value The riskScore to set.
       * @return This builder for chaining.
       */
      public Builder setRiskScore(int value) {
        
        riskScore_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 risk_score = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRiskScore() {
        bitField0_ = (bitField0_ & ~0x00000002);
        riskScore_ = 0;
        onChanged();
        return this;
      }

      private boolean mlUsed_ ;
      /**
       * <code>bool ml_used = 3;</code>
       * @return The mlUsed.
       */
      @java.lang.Override
      public boolean getMlUsed() {
        return mlUsed_;
      }
      /**
       * <code>bool ml_used = 3;</code>
       * @param value The mlUsed to set.
       * @return This builder for chaining.
       */
      public Builder setMlUsed(boolean value) {
        
        mlUsed_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool ml_used = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMlUsed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mlUsed_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sentinel.ScoreResponse)
    }

    // @@protoc_insertion_point(class_scope:sentinel.ScoreResponse)
    private static final sentinel.Scoring.ScoreResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sentinel.Scoring.ScoreResponse();
    }

    public static sentinel.Scoring.ScoreResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ScoreResponse>
        PARSER = new com.google.protobuf.AbstractParser<ScoreResponse>() {
      @java.lang.Override
      public ScoreResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ScoreResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ScoreResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sentinel.Scoring.ScoreResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_ScoreRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sentinel_ScoreRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_ScoreResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sentinel_ScoreResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rscoring.proto\022\010sentinel\"q\n\014ScoreReques" +
      "t\022\r\n\005tx_id\030\001 \001(\t\022\017\n\007user_id\030\002 \001(\t\022\016\n\006amo" +
      "unt\030\003 \001(\001\022\025\n\rhistory_count\030\004 \001(\005\022\032\n\022devi" +
      "ce_fingerprint\030\005 \001(\t\"C\n\rScoreResponse\022\r\n" +
      "\005tx_id\030\001 \001(\t\022\022\n\nrisk_score\030\002 \001(\005\022\017\n\007ml_u" +
      "sed\030\003 \001(\0102J\n\016ScoringService\0228\n\005Score\022\026.s" +
      "entinel.ScoreRequest\032\027.sentinel.ScoreRes" +
      "ponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sentinel_ScoreRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sentinel_ScoreRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sentinel_ScoreRequest_descriptor,
        new java.lang.String[] { "TxId", "UserId", "Amount", "HistoryCount", "DeviceFingerprint", });
    internal_static_sentinel_ScoreResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sentinel_ScoreResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sentinel_ScoreResponse_descriptor,
        new java.lang.String[] { "TxId", "RiskScore", "MlUsed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
