# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scoring.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'scoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rscoring.proto\x12\x08sentinel\"q\n\x0cScoreRequest\x12\r\n\x05tx_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x15\n\rhistory_count\x18\x04 \x01(\x05\x12\x1a\n\x12\x64\x65vice_fingerprint\x18\x05 \x01(\t\"C\n\rScoreResponse\x12\r\n\x05tx_id\x18\x01 \x01(\t\x12\x12\n\nrisk_score\x18\x02 \x01(\x05\x12\x0f\n\x07ml_used\x18\x03 \x01(\x08\x32J\n\x0eScoringService\x12\x38\n\x05Score\x12\x16.sentinel.ScoreRequest\x1a\x17.sentinel.ScoreResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCOREREQUEST']._serialized_start=27
  _globals['_SCOREREQUEST']._serialized_end=140
  _globals['_SCORERESPONSE']._serialized_start=142
  _globals['_SCORERESPONSE']._serialized_end=209
  _globals['_SCORINGSERVICE']._serialized_start=211
  _globals['_SCORINGSERVICE']._serialized_end=285
# @@protoc_insertion_point(module_scope)
